workers_dev = true
name = "my-react-router-worker"
compatibility_date = "2024-11-18"
main = "./workers/app.ts"
assets = { directory = "./build/client/" }
compatibility_flags = ["nodejs_compat"]

[vars]
TEST="Cloudflare Test"
REACT_ROUTER_PUBLIC_TEST1 = "React Router Public Test1"
REACT_ROUTER_PUBLIC_TEST2 = "React Router Public Test2"
